const HeaderXMLSE10 = {
	gfx: {
		$: {
			'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
			'xsi:noNamespaceSchemaLocation': 'Gfx-SE11.xsd',
		},
		displaySettings: [
			{
				$: {
					displayType: 'replace',
					position: 'specifyPositionInPixels',
					positionX: '0',
					positionY: '172',
					securityCode: '*',
					backColor: 'silver',
					titleBar: 'false',
					maximumTagUpdateRate: '1',
					focusHighlightColor: 'lime',
					disableFocusHighlight: 'false',
					size: 'specifySizeInPixels',
					width: '1920',
					height: '853',
					allowMultipleRunningCopies: 'false',
					cacheAfterDisplaying: 'false',
					sizeToMainWindow: 'false',
					showLastAcquiredValue: 'true',
					TrackScreenForNavigation: 'true',
					TrackName: 'High Shear Mixer PID',
					allowResizing: 'false',
					whenResized: 'scale',
					beepOnPress: 'false',
					highlightWhenCursorPassesOver: 'true',
					interactiveHighlightColor: 'white',
					displayOnScreenKeyboard: 'false',
					allowButtonActionOnError: 'true',
					fieldNotSelectedTextColor: 'black',
					fieldNotSelectedFillColor: 'white',
					fieldSelectedTextColor: 'black',
					fieldSelectedFillColor: 'white',
					fieldInErrorNotSelectedTextColor: 'black',
					fieldInErrorNotSelectedFillColor: 'red',
					fieldInErrorSelectedTextColor: 'white',
					fieldInErrorSelectedFillColor: 'red',
					startupCommand: '',
					shutdownCommand: '',
					useGradientStyle: 'false',
					endColor: 'teal',
					gradientStop: '50',
					gradientDirection: 'gradientDirectionHorizontal',
					gradientShadingStyle: 'gradientHorizontalFromRight',
				},
			},
		],
	},
};

module.exports = {
	HeaderSE10: HeaderXMLSE10,
};
